name: angelinashop
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  flutter_svg: ^2.0.17
  carousel_slider: ^5.0.0
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7
  flutter_html: ^3.0.0
  html: ^0.15.6
  path_provider: ^2.1.1
  shared_preferences: ^2.5.3
  webview_flutter: ^4.11.0
  shimmer: ^3.0.0
  intl:
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.0.7
  flutter_local_notifications: ^19.2.0
  timezone: ^0.10.1
  permission_handler: ^12.0.0+1
  #  workmanager: ^0.5.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  #  ios: true
  image_path: "assets/images/angelinaPic.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: El_Messiri
      fonts:
        - asset: assets/fonts/El_Messiri/static/ElMessiri-Bold.ttf
        - asset: assets/fonts/El_Messiri/static/ElMessiri-Medium.ttf
        - asset: assets/fonts/El_Messiri/static/ElMessiri-Regular.ttf
        - asset: assets/fonts/El_Messiri/static/ElMessiri-SemiBold.ttf
